# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43ommonReq.proto\"\xc5\x04\n\tCommonReq\x12\r\n\x05\x42\x44USS\x18\n \x01(\t\x12\x14\n\x0c_client_type\x18\x01 \x01(\x05\x12\x17\n\x0f_client_version\x18\x02 \x01(\t\x12\x12\n\n_client_id\x18\x03 \x01(\t\x12\x0c\n\x04\x61pid\x18\x04 \x01(\t\x12\x13\n\x0b_phone_imei\x18\x05 \x01(\t\x12\r\n\x05_from\x18\x06 \x01(\t\x12\x0c\n\x04\x63uid\x18\x07 \x01(\t\x12\x12\n\n_timestamp\x18\x08 \x01(\x03\x12\r\n\x05model\x18\t \x01(\t\x12\x0b\n\x03tbs\x18\x0b \x01(\t\x12\x10\n\x08net_type\x18\x0c \x01(\x05\x12\x13\n\x0bsubapp_type\x18\r \x01(\t\x12\x16\n\x0e_phone_newimei\x18\x0e \x01(\t\x12\n\n\x02ka\x18\x0f \x01(\t\x12\r\n\x05m_api\x18\x10 \x01(\t\x12\x0f\n\x07m_logid\x18\x11 \x01(\t\x12\x0e\n\x06m_cost\x18\x12 \x01(\t\x12\x10\n\x08m_result\x18\x13 \x01(\t\x12\x10\n\x08m_size_u\x18\x14 \x01(\t\x12\x10\n\x08m_size_d\x18\x15 \x01(\t\x12\x11\n\tsmallflow\x18\x16 \x01(\t\x12\x0c\n\x04sign\x18\x17 \x01(\t\x12\x10\n\x08pversion\x18\x18 \x01(\t\x12\r\n\x05\x62rand\x18\x1a \x01(\t\x12\x12\n\nbrand_type\x18\x1b \x01(\t\x12\x18\n\x10lego_lib_version\x18\x1c \x01(\t\x12\x0f\n\x07\x61pplist\x18\x1d \x01(\t\x12\x0e\n\x06stoken\x18\x1e \x01(\t\x12\x0c\n\x04z_id\x18\x1f \x01(\t\x12\x14\n\x0c\x63uid_galaxy2\x18  \x01(\t\x12\x10\n\x08\x63uid_gid\x18! \x01(\tb\x06proto3')



_COMMONREQ = DESCRIPTOR.message_types_by_name['CommonReq']
CommonReq = _reflection.GeneratedProtocolMessageType('CommonReq', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQ,
  '__module__' : 'CommonReq_pb2'
  # @@protoc_insertion_point(class_scope:CommonReq)
  })
_sym_db.RegisterMessage(CommonReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONREQ._serialized_start=20
  _COMMONREQ._serialized_end=601
# @@protoc_insertion_point(module_scope)
