# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForumInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x46orumInfo.proto\"_\n\tForumInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nmember_num\x18\t \x01(\x05\x12\x12\n\nthread_num\x18\n \x01(\x05\x12\x10\n\x08post_num\x18\x0c \x01(\x05\x62\x06proto3')



_FORUMINFO = DESCRIPTOR.message_types_by_name['ForumInfo']
ForumInfo = _reflection.GeneratedProtocolMessageType('ForumInfo', (_message.Message,), {
  'DESCRIPTOR' : _FORUMINFO,
  '__module__' : 'ForumInfo_pb2'
  # @@protoc_insertion_point(class_scope:ForumInfo)
  })
_sym_db.RegisterMessage(ForumInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORUMINFO._serialized_start=19
  _FORUMINFO._serialized_end=114
# @@protoc_insertion_point(module_scope)
