# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetUserInfoResIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import User_pb2 as User__pb2
from . import Error_pb2 as Error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetUserInfoResIdl.proto\x1a\nUser.proto\x1a\x0b\x45rror.proto\"t\n\x11GetUserInfoResIdl\x12\x15\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.Error\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1a.GetUserInfoResIdl.DataRes\x1a\x1e\n\x07\x44\x61taRes\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.Userb\x06proto3')



_GETUSERINFORESIDL = DESCRIPTOR.message_types_by_name['GetUserInfoResIdl']
_GETUSERINFORESIDL_DATARES = _GETUSERINFORESIDL.nested_types_by_name['DataRes']
GetUserInfoResIdl = _reflection.GeneratedProtocolMessageType('GetUserInfoResIdl', (_message.Message,), {

  'DataRes' : _reflection.GeneratedProtocolMessageType('DataRes', (_message.Message,), {
    'DESCRIPTOR' : _GETUSERINFORESIDL_DATARES,
    '__module__' : 'GetUserInfoResIdl_pb2'
    # @@protoc_insertion_point(class_scope:GetUserInfoResIdl.DataRes)
    })
  ,
  'DESCRIPTOR' : _GETUSERINFORESIDL,
  '__module__' : 'GetUserInfoResIdl_pb2'
  # @@protoc_insertion_point(class_scope:GetUserInfoResIdl)
  })
_sym_db.RegisterMessage(GetUserInfoResIdl)
_sym_db.RegisterMessage(GetUserInfoResIdl.DataRes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSERINFORESIDL._serialized_start=52
  _GETUSERINFORESIDL._serialized_end=168
  _GETUSERINFORESIDL_DATARES._serialized_start=138
  _GETUSERINFORESIDL_DATARES._serialized_end=168
# @@protoc_insertion_point(module_scope)
