# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetUserInfoReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetUserInfoReqIdl.proto\x1a\x0f\x43ommonReq.proto\"q\n\x11GetUserInfoReqIdl\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.GetUserInfoReqIdl.DataReq\x1a\x32\n\x07\x44\x61taReq\x12\x1a\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\n.CommonReq\x12\x0b\n\x03uid\x18\x02 \x01(\x03\x62\x06proto3')



_GETUSERINFOREQIDL = DESCRIPTOR.message_types_by_name['GetUserInfoReqIdl']
_GETUSERINFOREQIDL_DATAREQ = _GETUSERINFOREQIDL.nested_types_by_name['DataReq']
GetUserInfoReqIdl = _reflection.GeneratedProtocolMessageType('GetUserInfoReqIdl', (_message.Message,), {

  'DataReq' : _reflection.GeneratedProtocolMessageType('DataReq', (_message.Message,), {
    'DESCRIPTOR' : _GETUSERINFOREQIDL_DATAREQ,
    '__module__' : 'GetUserInfoReqIdl_pb2'
    # @@protoc_insertion_point(class_scope:GetUserInfoReqIdl.DataReq)
    })
  ,
  'DESCRIPTOR' : _GETUSERINFOREQIDL,
  '__module__' : 'GetUserInfoReqIdl_pb2'
  # @@protoc_insertion_point(class_scope:GetUserInfoReqIdl)
  })
_sym_db.RegisterMessage(GetUserInfoReqIdl)
_sym_db.RegisterMessage(GetUserInfoReqIdl.DataReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSERINFOREQIDL._serialized_start=44
  _GETUSERINFOREQIDL._serialized_end=157
  _GETUSERINFOREQIDL_DATAREQ._serialized_start=107
  _GETUSERINFOREQIDL_DATAREQ._serialized_end=157
# @@protoc_insertion_point(module_scope)
