# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Page.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nPage.proto\"T\n\x04Page\x12\x14\n\x0c\x63urrent_page\x18\x03 \x01(\x05\x12\x10\n\x08has_more\x18\x06 \x01(\x05\x12\x10\n\x08has_prev\x18\x07 \x01(\x05\x12\x12\n\ntotal_page\x18\x05 \x01(\x05\x62\x06proto3')



_PAGE = DESCRIPTOR.message_types_by_name['Page']
Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : _PAGE,
  '__module__' : 'Page_pb2'
  # @@protoc_insertion_point(class_scope:Page)
  })
_sym_db.RegisterMessage(Page)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAGE._serialized_start=14
  _PAGE._serialized_end=98
# @@protoc_insertion_point(module_scope)
