# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbContent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fPbContent.proto\"\xbe\x02\n\tPbContent\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x0b\n\x03src\x18\x04 \x01(\t\x12\r\n\x05\x62size\x18\x05 \x01(\t\x12\x0f\n\x07\x62ig_src\x18\x06 \x01(\t\x12\x10\n\x08\x62ig_size\x18\x07 \x01(\t\x12\x0f\n\x07\x63\x64n_src\x18\x08 \x01(\t\x12\x13\n\x0b\x62ig_cdn_src\x18\t \x01(\t\x12\x0f\n\x07imgtype\x18\n \x01(\t\x12\x11\n\tvoice_md5\x18\x0c \x01(\t\x12\r\n\x05width\x18\x12 \x01(\r\x12\x0e\n\x06height\x18\x13 \x01(\r\x12\x13\n\x0bpacket_name\x18\x14 \x01(\t\x12\x11\n\tphonetype\x18\x15 \x01(\t\x12\x0e\n\x06\x65_type\x18\x18 \x01(\r\x12\x12\n\norigin_src\x18\x19 \x01(\t\x12\x13\n\x0borigin_size\x18\x1b \x01(\rb\x06proto3')



_PBCONTENT = DESCRIPTOR.message_types_by_name['PbContent']
PbContent = _reflection.GeneratedProtocolMessageType('PbContent', (_message.Message,), {
  'DESCRIPTOR' : _PBCONTENT,
  '__module__' : 'PbContent_pb2'
  # @@protoc_insertion_point(class_scope:PbContent)
  })
_sym_db.RegisterMessage(PbContent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBCONTENT._serialized_start=20
  _PBCONTENT._serialized_end=338
# @@protoc_insertion_point(module_scope)
