# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbFloorReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PbFloorReqIdl.proto\x1a\x0f\x43ommonReq.proto\"\x81\x01\n\rPbFloorReqIdl\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.PbFloorReqIdl.DataReq\x1aJ\n\x07\x44\x61taReq\x12\x1a\n\x06\x63ommon\x18\t \x01(\x0b\x32\n.CommonReq\x12\n\n\x02kz\x18\x01 \x01(\x03\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\n\n\x02pn\x18\x04 \x01(\x05\x62\x06proto3')



_PBFLOORREQIDL = DESCRIPTOR.message_types_by_name['PbFloorReqIdl']
_PBFLOORREQIDL_DATAREQ = _PBFLOORREQIDL.nested_types_by_name['DataReq']
PbFloorReqIdl = _reflection.GeneratedProtocolMessageType('PbFloorReqIdl', (_message.Message,), {

  'DataReq' : _reflection.GeneratedProtocolMessageType('DataReq', (_message.Message,), {
    'DESCRIPTOR' : _PBFLOORREQIDL_DATAREQ,
    '__module__' : 'PbFloorReqIdl_pb2'
    # @@protoc_insertion_point(class_scope:PbFloorReqIdl.DataReq)
    })
  ,
  'DESCRIPTOR' : _PBFLOORREQIDL,
  '__module__' : 'PbFloorReqIdl_pb2'
  # @@protoc_insertion_point(class_scope:PbFloorReqIdl)
  })
_sym_db.RegisterMessage(PbFloorReqIdl)
_sym_db.RegisterMessage(PbFloorReqIdl.DataReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBFLOORREQIDL._serialized_start=41
  _PBFLOORREQIDL._serialized_end=170
  _PBFLOORREQIDL_DATAREQ._serialized_start=96
  _PBFLOORREQIDL_DATAREQ._serialized_end=170
# @@protoc_insertion_point(module_scope)
