# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbPageReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PbPageReqIdl.proto\x1a\x0f\x43ommonReq.proto\"\xab\x02\n\x0cPbPageReqIdl\x12#\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x15.PbPageReqIdl.DataReq\x1a\xf5\x01\n\x07\x44\x61taReq\x12\x1a\n\x06\x63ommon\x18\x19 \x01(\x0b\x32\n.CommonReq\x12\n\n\x02kz\x18\x04 \x01(\x03\x12\n\n\x02lz\x18\x05 \x01(\x05\x12\t\n\x01r\x18\x06 \x01(\x05\x12\x12\n\nwith_floor\x18\x08 \x01(\x05\x12\x10\n\x08\x66loor_rn\x18\t \x01(\x05\x12\n\n\x02rn\x18\r \x01(\x05\x12\x0e\n\x06q_type\x18\x11 \x01(\x05\x12\n\n\x02pn\x18\x12 \x01(\x05\x12\x17\n\x0fis_comm_reverse\x18! \x01(\x05\x12\x14\n\x0cis_jumpfloor\x18\" \x01(\x05\x12\x15\n\rjumpfloor_num\x18# \x01(\x05\x12\x17\n\x0f\x66loor_sort_type\x18J \x01(\x05\x62\x06proto3')



_PBPAGEREQIDL = DESCRIPTOR.message_types_by_name['PbPageReqIdl']
_PBPAGEREQIDL_DATAREQ = _PBPAGEREQIDL.nested_types_by_name['DataReq']
PbPageReqIdl = _reflection.GeneratedProtocolMessageType('PbPageReqIdl', (_message.Message,), {

  'DataReq' : _reflection.GeneratedProtocolMessageType('DataReq', (_message.Message,), {
    'DESCRIPTOR' : _PBPAGEREQIDL_DATAREQ,
    '__module__' : 'PbPageReqIdl_pb2'
    # @@protoc_insertion_point(class_scope:PbPageReqIdl.DataReq)
    })
  ,
  'DESCRIPTOR' : _PBPAGEREQIDL,
  '__module__' : 'PbPageReqIdl_pb2'
  # @@protoc_insertion_point(class_scope:PbPageReqIdl)
  })
_sym_db.RegisterMessage(PbPageReqIdl)
_sym_db.RegisterMessage(PbPageReqIdl.DataReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBPAGEREQIDL._serialized_start=40
  _PBPAGEREQIDL._serialized_end=339
  _PBPAGEREQIDL_DATAREQ._serialized_start=94
  _PBPAGEREQIDL_DATAREQ._serialized_end=339
# @@protoc_insertion_point(module_scope)
