# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReplyMeReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ReplyMeReqIdl.proto\x1a\x0f\x43ommonReq.proto\"h\n\rReplyMeReqIdl\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.ReplyMeReqIdl.DataReq\x1a\x31\n\x07\x44\x61taReq\x12\n\n\x02pn\x18\x01 \x01(\t\x12\x1a\n\x06\x63ommon\x18\x03 \x01(\x0b\x32\n.CommonReqb\x06proto3')



_REPLYMEREQIDL = DESCRIPTOR.message_types_by_name['ReplyMeReqIdl']
_REPLYMEREQIDL_DATAREQ = _REPLYMEREQIDL.nested_types_by_name['DataReq']
ReplyMeReqIdl = _reflection.GeneratedProtocolMessageType('ReplyMeReqIdl', (_message.Message,), {

  'DataReq' : _reflection.GeneratedProtocolMessageType('DataReq', (_message.Message,), {
    'DESCRIPTOR' : _REPLYMEREQIDL_DATAREQ,
    '__module__' : 'ReplyMeReqIdl_pb2'
    # @@protoc_insertion_point(class_scope:ReplyMeReqIdl.DataReq)
    })
  ,
  'DESCRIPTOR' : _REPLYMEREQIDL,
  '__module__' : 'ReplyMeReqIdl_pb2'
  # @@protoc_insertion_point(class_scope:ReplyMeReqIdl)
  })
_sym_db.RegisterMessage(ReplyMeReqIdl)
_sym_db.RegisterMessage(ReplyMeReqIdl.DataReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLYMEREQIDL._serialized_start=40
  _REPLYMEREQIDL._serialized_end=144
  _REPLYMEREQIDL_DATAREQ._serialized_start=95
  _REPLYMEREQIDL_DATAREQ._serialized_end=144
# @@protoc_insertion_point(module_scope)
