# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfileReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ProfileReqIdl.proto\x1a\x0f\x43ommonReq.proto\"\xcc\x01\n\rProfileReqIdl\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.ProfileReqIdl.DataReq\x1a\x94\x01\n\x07\x44\x61taReq\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x17\n\x0fneed_post_count\x18\x02 \x01(\r\x12\x12\n\nfriend_uid\x18\x03 \x01(\x03\x12\n\n\x02pn\x18\x06 \x01(\r\x12\n\n\x02rn\x18\x07 \x01(\r\x12\x1a\n\x06\x63ommon\x18\t \x01(\x0b\x32\n.CommonReq\x12\x1b\n\x13\x66riend_uid_portrait\x18\x10 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfileReqIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILEREQIDL._serialized_start=41
  _PROFILEREQIDL._serialized_end=245
  _PROFILEREQIDL_DATAREQ._serialized_start=97
  _PROFILEREQIDL_DATAREQ._serialized_end=245
# @@protoc_insertion_point(module_scope)
