line-length = 120
target-version = "py311"

extend-exclude = ["*_pb2.py"]

preview = true

[lint]
explicit-preview-rules = true
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "YTT",
    "ASYNC",
    "B",
    "A",
    "C4",
    "FA",
    "ICN",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "T10",
    "T20",
    "PT",
    "Q",
    "RSE",
    "RUF",
    "SLOT",
    "TC",
    "PTH",
    "NPY",
    "PERF",
    "FURB",
]

ignore = [
    "line-too-long",
    "unsorted-dunder-slots",
]
allowed-confusables = ["，", "：", "（", "）"]

[lint.per-file-ignores]
"__init__.py" = ["unused-import"]
"typing.py" = ["unused-import"]

[lint.isort]
known-first-party = ["aiotieba"]

[format]
docstring-code-format = true
line-ending = "lf"
