# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatDatabase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12StatDatabase.proto\"\x82\x03\n\x10RiskUserDatabase\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.RiskUserDatabase.RiskUser\x1a\xc2\x02\n\x08RiskUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08portrait\x18\x02 \x01(\t\x12\x15\n\rportrait_hash\x18\x03 \x01(\t\x12\x30\n\x06\x66orums\x18\x0e \x03(\x0b\x32 .RiskUserDatabase.RiskUser.Forum\x12\x32\n\x07threads\x18\x0f \x03(\x0b\x32!.RiskUserDatabase.RiskUser.Thread\x1a\x30\n\x05\x46orum\x12\x0b\n\x03\x66id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x05\x1a\x64\n\x06Thread\x12\x0b\n\x03\x66id\x18\x01 \x01(\x05\x12\x0b\n\x03tid\x18\x02 \x01(\x03\x12\r\n\x05\x61gree\x18\x03 \x01(\x05\x12\x10\n\x08view_num\x18\x04 \x01(\x05\x12\x11\n\treply_num\x18\x05 \x01(\x05\x12\x0c\n\x04text\x18\x06 \x01(\t\"R\n\tForumList\x12 \n\x06\x66orums\x18\x01 \x03(\x0b\x32\x10.ForumList.Forum\x1a#\n\x05\x46orum\x12\x0b\n\x03\x66id\x18\x01 \x01(\x05\x12\r\n\x05\x66name\x18\x02 \x01(\t\"\x88\x01\n\x10RankUserDatabase\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.RankUserDatabase.RankUser\x1aI\n\x08RankUser\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x05\x12\x0e\n\x06is_vip\x18\x04 \x01(\x05\x62\x06proto3')



_RISKUSERDATABASE = DESCRIPTOR.message_types_by_name['RiskUserDatabase']
_RISKUSERDATABASE_RISKUSER = _RISKUSERDATABASE.nested_types_by_name['RiskUser']
_RISKUSERDATABASE_RISKUSER_FORUM = _RISKUSERDATABASE_RISKUSER.nested_types_by_name['Forum']
_RISKUSERDATABASE_RISKUSER_THREAD = _RISKUSERDATABASE_RISKUSER.nested_types_by_name['Thread']
_FORUMLIST = DESCRIPTOR.message_types_by_name['ForumList']
_FORUMLIST_FORUM = _FORUMLIST.nested_types_by_name['Forum']
_RANKUSERDATABASE = DESCRIPTOR.message_types_by_name['RankUserDatabase']
_RANKUSERDATABASE_RANKUSER = _RANKUSERDATABASE.nested_types_by_name['RankUser']
RiskUserDatabase = _reflection.GeneratedProtocolMessageType('RiskUserDatabase', (_message.Message,), {

  'RiskUser' : _reflection.GeneratedProtocolMessageType('RiskUser', (_message.Message,), {

    'Forum' : _reflection.GeneratedProtocolMessageType('Forum', (_message.Message,), {
      'DESCRIPTOR' : _RISKUSERDATABASE_RISKUSER_FORUM,
      '__module__' : 'StatDatabase_pb2'
      # @@protoc_insertion_point(class_scope:RiskUserDatabase.RiskUser.Forum)
      })
    ,

    'Thread' : _reflection.GeneratedProtocolMessageType('Thread', (_message.Message,), {
      'DESCRIPTOR' : _RISKUSERDATABASE_RISKUSER_THREAD,
      '__module__' : 'StatDatabase_pb2'
      # @@protoc_insertion_point(class_scope:RiskUserDatabase.RiskUser.Thread)
      })
    ,
    'DESCRIPTOR' : _RISKUSERDATABASE_RISKUSER,
    '__module__' : 'StatDatabase_pb2'
    # @@protoc_insertion_point(class_scope:RiskUserDatabase.RiskUser)
    })
  ,
  'DESCRIPTOR' : _RISKUSERDATABASE,
  '__module__' : 'StatDatabase_pb2'
  # @@protoc_insertion_point(class_scope:RiskUserDatabase)
  })
_sym_db.RegisterMessage(RiskUserDatabase)
_sym_db.RegisterMessage(RiskUserDatabase.RiskUser)
_sym_db.RegisterMessage(RiskUserDatabase.RiskUser.Forum)
_sym_db.RegisterMessage(RiskUserDatabase.RiskUser.Thread)

ForumList = _reflection.GeneratedProtocolMessageType('ForumList', (_message.Message,), {

  'Forum' : _reflection.GeneratedProtocolMessageType('Forum', (_message.Message,), {
    'DESCRIPTOR' : _FORUMLIST_FORUM,
    '__module__' : 'StatDatabase_pb2'
    # @@protoc_insertion_point(class_scope:ForumList.Forum)
    })
  ,
  'DESCRIPTOR' : _FORUMLIST,
  '__module__' : 'StatDatabase_pb2'
  # @@protoc_insertion_point(class_scope:ForumList)
  })
_sym_db.RegisterMessage(ForumList)
_sym_db.RegisterMessage(ForumList.Forum)

RankUserDatabase = _reflection.GeneratedProtocolMessageType('RankUserDatabase', (_message.Message,), {

  'RankUser' : _reflection.GeneratedProtocolMessageType('RankUser', (_message.Message,), {
    'DESCRIPTOR' : _RANKUSERDATABASE_RANKUSER,
    '__module__' : 'StatDatabase_pb2'
    # @@protoc_insertion_point(class_scope:RankUserDatabase.RankUser)
    })
  ,
  'DESCRIPTOR' : _RANKUSERDATABASE,
  '__module__' : 'StatDatabase_pb2'
  # @@protoc_insertion_point(class_scope:RankUserDatabase)
  })
_sym_db.RegisterMessage(RankUserDatabase)
_sym_db.RegisterMessage(RankUserDatabase.RankUser)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RISKUSERDATABASE._serialized_start=23
  _RISKUSERDATABASE._serialized_end=409
  _RISKUSERDATABASE_RISKUSER._serialized_start=87
  _RISKUSERDATABASE_RISKUSER._serialized_end=409
  _RISKUSERDATABASE_RISKUSER_FORUM._serialized_start=259
  _RISKUSERDATABASE_RISKUSER_FORUM._serialized_end=307
  _RISKUSERDATABASE_RISKUSER_THREAD._serialized_start=309
  _RISKUSERDATABASE_RISKUSER_THREAD._serialized_end=409
  _FORUMLIST._serialized_start=411
  _FORUMLIST._serialized_end=493
  _FORUMLIST_FORUM._serialized_start=458
  _FORUMLIST_FORUM._serialized_end=493
  _RANKUSERDATABASE._serialized_start=496
  _RANKUSERDATABASE._serialized_end=632
  _RANKUSERDATABASE_RANKUSER._serialized_start=559
  _RANKUSERDATABASE_RANKUSER._serialized_end=632
# @@protoc_insertion_point(module_scope)
