# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PostInfoList.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PollInfo_pb2 as PollInfo__pb2
from . import PbContent_pb2 as PbContent__pb2
from . import Agree_pb2 as Agree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PostInfoList.proto\x1a\x0ePollInfo.proto\x1a\x0fPbContent.proto\x1a\x0b\x41gree.proto\"\xa2\x02\n\x0cPostInfoList\x12\x10\n\x08\x66orum_id\x18\x01 \x01(\x03\x12\x11\n\tthread_id\x18\x02 \x01(\x03\x12\x0f\n\x07post_id\x18\x03 \x01(\x03\x12\x13\n\x0b\x63reate_time\x18\x05 \x01(\r\x12\x12\n\nforum_name\x18\x06 \x01(\t\x12\r\n\x05title\x18\x07 \x01(\t\x12\x11\n\treply_num\x18\x11 \x01(\r\x12\x0f\n\x07user_id\x18\x12 \x01(\x03\x12\x1c\n\tpoll_info\x18\x1c \x01(\x0b\x32\t.PollInfo\x12\x10\n\x08\x66req_num\x18! \x01(\x05\x12\x11\n\tshare_num\x18\' \x01(\x05\x12\x15\n\x05\x61gree\x18( \x01(\x0b\x32\x06.Agree\x12&\n\x12\x66irst_post_content\x18\x31 \x03(\x0b\x32\n.PbContentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PostInfoList_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTINFOLIST._serialized_start=69
  _POSTINFOLIST._serialized_end=359
# @@protoc_insertion_point(module_scope)
