# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetUserByTiebaUidReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..._protobuf import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dGetUserByTiebaUidReqIdl.proto\x1a\x0f\x43ommonReq.proto\"\x83\x01\n\x17GetUserByTiebaUidReqIdl\x12.\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32 .GetUserByTiebaUidReqIdl.DataReq\x1a\x38\n\x07\x44\x61taReq\x12\x1a\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\n.CommonReq\x12\x11\n\ttieba_uid\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetUserByTiebaUidReqIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSERBYTIEBAUIDREQIDL._serialized_start=51
  _GETUSERBYTIEBAUIDREQIDL._serialized_end=182
  _GETUSERBYTIEBAUIDREQIDL_DATAREQ._serialized_start=126
  _GETUSERBYTIEBAUIDREQIDL_DATAREQ._serialized_end=182
# @@protoc_insertion_point(module_scope)
