# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SearchPostForumReqIdl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonReq_pb2 as CommonReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSearchPostForumReqIdl.proto\x1a\x0f\x43ommonReq.proto\"z\n\x15SearchPostForumReqIdl\x12,\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1e.SearchPostForumReqIdl.DataReq\x1a\x33\n\x07\x44\x61taReq\x12\x1a\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\n.CommonReq\x12\x0c\n\x04word\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SearchPostForumReqIdl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHPOSTFORUMREQIDL._serialized_start=48
  _SEARCHPOSTFORUMREQIDL._serialized_end=170
  _SEARCHPOSTFORUMREQIDL_DATAREQ._serialized_start=119
  _SEARCHPOSTFORUMREQIDL_DATAREQ._serialized_end=170
# @@protoc_insertion_point(module_scope)
