name: CI-beta

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "CPython version to test"
        required: false
        type: string
        default: "3.16"

jobs:
  test-beta:
    name: Test-beta
    runs-on: ubuntu-slim

    environment: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: develop

      - name: Setup UV
        uses: astral-sh/setup-uv@v10.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        env:
          TB_BDUSS: ${{ secrets.BDUSS }}
          TB_STOKEN: ${{ secrets.STOKEN }}
        run: uv run pytest
